spring.application.name=ecom-orderservice
spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=5000
#logging.level.com.harsh.microservices.ecom_orderservice.client=DEBUG